# Generated by Django 6.0.2 on 2026-02-13 22:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marques/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('modele', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('annee', models.PositiveIntegerField()),
                ('kilometrage', models.PositiveIntegerField()),
                ('energie', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('ELECTRIQUE', 'Électrique'), ('HYBRIDE', 'Hybride')], max_length=20)),
                ('boite_vitesse', models.CharField(choices=[('MANUELLE', 'Manuelle'), ('AUTOMATIQUE', 'Automatique')], max_length=20)),
                ('description', models.TextField()),
                ('image_principale', models.ImageField(upload_to='vehicules/principales/')),
                ('est_disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='car_shop.marque')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ImageVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicules/galerie/')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_galerie', to='car_shop.vehicule')),
            ],
        ),
    ]
